export const POST_EMPLOYEE = "POST_EMPLOYEE";
export const POST_EMPLOYEE_FAILED = "POST_EMPLOYEE_FAILED";
export const POST_EMPLOYEE_SUCCEEDED = "POST_EMPLOYEE_SUCCEEDED";

export const IMPORT_ALL_EMPLOYEES = "IMPORT_ALL_EMPLOYEES";
export const IMPORT_ALL_EMPLOYEES_FAILED = "IMPORT_ALL_EMPLOYEES_FAILED";
export const IMPORT_ALL_EMPLOYEES_SUCCEEDED = "IMPORT_ALL_EMPLOYEES_SUCCEEDED";

export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_EMPLOYEES_FAILED = "FETCH_EMPLOYEES_FAILED";
export const FETCH_EMPLOYEES_SUCCEEDED = "FETCH_EMPLOYEES_SUCCEEDED";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";
export const DELETE_EMPLOYEE_SUCCEEDED = "DELETE_EMPLOYEE_SUCCEEDED";

export const PUT_EMPLOYEE = "PUT_EMPLOYEE";
export const PUT_EMPLOYEE_FAILED = "PUT_EMPLOYEE_FAILED";
export const PUT_EMPLOYEE_SUCCEEDED = "PUT_EMPLOYEE_SUCCEEDED";

export const DELETE_ALL_EMPLOYEES = "DELETE_ALL_EMPLOYEES";
export const DELETE_ALL_EMPLOYEES_FAILED = "DELETE_ALL_EMPLOYEES_FAILED";
export const DELETE_ALL_EMPLOYEES_SUCCEEDED = "DELETE_ALL_EMPLOYEES_SUCCEEDED";

export const TERMINATE_EMPLOYEE = "TERMINATE_EMPLOYEE";
export const TERMINATE_EMPLOYEE_SUCCEEDED = "TERMINATE_EMPLOYEE_SUCCEEDED";
export const TERMINATE_EMPLOYEE_FAILED = "TERMINATE_EMPLOYEE_FAILED";
