export const POST_SHARE_PRICE_SUCCEEDED = "POST_SHARE_PRICE_SUCCEEDED";
export const POST_SHARE_PRICE_FAILED = "POST_SHARE_PRICE_FAILED";
export const POST_SHARE_PRICE = "POST_SHARE_PRICE";

export const FETCH_SHARE_PRICE_SUCCEEDED = "FETCH_SHARE_PRICE_SUCCEEDED";
export const FETCH_SHARE_PRICE_FAILED = "FETCH_SHARE_PRICE_FAILED";
export const FETCH_SHARE_PRICE = "FETCH_SHARE_PRICE";

export const DELETE_SHARE_PRICE_SUCCEEDED = "DELETE_SHARE_PRICE_SUCCEEDED";
export const DELETE_SHARE_PRICE_FAILED = "DELETE_SHARE_PRICE_FAILED";
export const DELETE_SHARE_PRICE = "DELETE_SHARE_PRICE";