import {Entity} from "../../entity/entity-reducer";
import {Moment} from "moment";
import {Employee, MobilityEntry} from "../../employees/employee-reducer";
import {ExcelSheetAwardLine} from "../../awards/award-reducer";
import {TransactionType} from "../reports";

export interface ReportLine {
    id: string,
    integerId: number,
    internal_employee_id?: string,
    vesting_event_id: string,
    programId: string,
    entityName: string,
    employee: Employee,
    entity: Entity,
    planName: string,
    subplanName: string,
    employeeName: string,
    transactionType: TransactionType
    grantDate: Moment,
    transactionDate: Moment,
    vestingDate: Moment,
    expiryDate: Moment,
    valid_from_date?: Moment
    valid_to_date?: Moment
    strikePrice: number,
    instrumentType: string,
    quantity: number,
    earnedFrom?: Moment,
    earnedTo?: Moment,
    earnedOB?: number,
    earnedDaysOB?: number,
    openingBalance?: number,
    periodCost?: number,
    earnedPeriod?: number,
    closingBalance?: number,
    earnedCB?: number,
    earnedDaysCB?: number,
    unamortized?: number,
    fairValue?: number,
    totalCost?: number,
    totalTurnoverRate?: number,
    annualTurnoverRate?: number,
    turnoverEffectOB?: number,
    costOBIncTurnover?: number,
    periodCostIncTurnover?: number,
    turnoverEffectCB?: number,
    costCBIncTurnover?: number,
    costUnamortizedIncTurnover?: number,
    transactions_to_terminate?: ExcelSheetAwardLine[],
    mobility?: MobilityEntry[],
    socSecRate?: number,
}

export interface PrintableReportLine {
    id: string,
    integerId: string,
    internal_employee_id?: string,
    vesting_event_id: string,
    entityName: string,
    planName: string,
    subplanName: string,
    employeeName: string,
    transactionType: string
    grantDate: string,
    transactionDate: string,
    vestingDate: string,
    expiryDate: string,
    strikePrice: string,
    quantity: string,
    sharePriceOB: string,
    earnedOB: string,
    earnedDaysOB: string,
    openingBalance: string,
    periodCost: string,
    earnedPeriod: string,
    closingBalance: string,
    sharePriceCB: string,
    earnedCB: string,
    earnedDaysCB: string,
    unamortized: string,
    fairValue: string,
    totalCost: string,
    totalTurnoverRate: string,
    annualTurnoverRate: string,
    turnoverEffectOB: string,
    costOBIncTurnover: string,
    periodCostIncTurnover: string,
    turnoverEffectCB: string,
    costCBIncTurnover: string,
    costUnamortizedIncTurnover: string,
}
