export const FETCH_TEXTS = "FETCH_TEXTS";
export const FETCH_TEXTS_FAILED = "FETCH_TEXTS_FAILED";
export const FETCH_TEXTS_SUCCEEDED = "FETCH_TEXTS_SUCCEEDED";

export const PUT_TEXT = "PUT_TEXT";
export const PUT_TEXT_FAILED = "PUT_TEXT_FAILED";
export const PUT_TEXT_SUCCEEDED = "PUT_TEXT_SUCCEEDED";

export const UPDATE_DEFAULT_TEXTS = "UPDATE_DEFAULT_TEXTS";
export const UPDATE_DEFAULT_TEXTS_FAILED = "UPDATE_DEFAULT_TEXTS_FAILED";
export const UPDATE_DEFAULT_TEXTS_SUCCEEDED = "UPDATE_DEFAULT_TEXTS_SUCCEEDED";
