module.exports = {
   "acceptdocuments.modal.title": "Action Required",
   "acceptdocuments.modal.accepted.title": "Accepted",
   "acceptdocuments.modal.accepted.content": "Your documents are available to view within the portal",
   "purchase.title": "Purchase",
   "purchase.acceptdocument.header": "Read and accept purchase agreement",
   "purchase.acceptdocument.body": "The terms for your purchase",
   "purchase.quantity.body": "The price for each {instrumentTermSingular} is {price}",
   "purchase.sharedepository.header": "In which Share Depository Account would you like to receive your {instrumentTermPlural}?",
   "purchase.sharedepository.body": "Kanskje noe om prosessen for overføring? Og eventuelt om binding?",
   "purchase.confirm.header": "Confirm order",
   "purchase.confirm.body.1": "You have chosen to purchase {numberOfInstruments} {instrumentTermPlural} for a price per {instrumentTermSingular} of {pricePerInstrument}.",
   "purchase.confirm.body.2": "The total price for all {instrumentTermPlural} is {totalAmount}",
   "purchase.not.possible.notinwindow.header": "Not in a purchase window",
   "purchase.not.possible.notinwindow.description": "Wait for a purchase window to open in order to purchase.",
   "purchase.not.possible.nopurchasableinstruments.header": "Purchase not possible",
   "purchase.not.possible.nopurchasableinstruments.description": "No purchasable instruments available",
   "purchase.confirm.description": "Please transfer the total price of {totalPrice} using the payment information below. The full amount must be transferred and registered into the account before {transferDeadline}. If payment is not registered in time, the purchase will not be valid. The transfer of funds might take several days and we encourage you to do this as soon as possible in order for the payment to be registered on time. A confirmation email with the payment information will be sent to you upon confirmation of the order.",
   "performace.information": "Some or all instruments above are subject to performance criteria",
   "performace.information.question": "Your instruments are subject to performance, meaning that there exists one or more additional criteria that must be fulfilled in order to earn the instruments. View your agreement documents to see your specific performance criteria",
   "exercise.title": "Exercise {instrumentName}",
   "overview.exercise.in.window.description": "Current exercise window closes on {endDate}",
   "overview.exercise.not.in.window.next.window.description": "Exercising will be available when you have exercisible options and we're in an exercise window. Next exercise window will be from {from} to {to}.",
   "overview.exercise.not.in.window.no.next.window.description": "Exercising will be available when you have exercisible options and we're in an exercise window. When the next exercise window opens will be determined by your employer.",
   "exercise.exercise.note": "Only exercisable instruments are shown in the table",
   "exercise.quantity.body": "Note that Estimated gain below is based on last available share price ({sharePrice}). Actual gain will depend on market prices following the exercise window.",
   "exercise.quantity.title": "How many of the exercisible {instrumentTerm} would you like to exercise?",
   "exercise.type.title": "How would you like to exercise?",
   "exercise.type.exerciseandhold.terms": "'Your shares will be transferred to the submitted share depository account dependent on the completion of the following. 1) Total strike amount for the corresponding shares must be transferred to the company supplied bank account number, and verified by the company, 2) any documentation needed for the share capital increase (and related) with respect to governmental (or other institutions) requirements, must be fulfilled by the company and you as the participant, 3) You as the participant must supply a valid Share Depository Account. If the total strike amount is not registered on the company account within the given deadline, the options will not be exercised'",
   "exercise.type.exerciseandhold.header": "1. Exercise & Hold",
   "exercise.type.exerciseandhold.description": "Exercise your {instrumentName} and cover the total strike amount using your own funds, receive all shares following the exercise to your share depository account",
   "exercise.type.exerciseandsell.header": "2. Exercise & Sell",
   "exercise.type.exerciseandsell.description": "Exercise your {instrumentName}, broker will cover the total strike amount, broker will receive shares and sell all the received shares in the market. You will receive net gain as salary, after total strike amount and broker fee is covered",
   "exercise.type.exerciseandselltocover.header": "3. Exercise & Sell to cover",
   "exercise.type.exerciseandselltocover.description": "Exercise your {instrumentName}, broker will cover the total strike amount, broker will receive shares and sell all the received shares in the market. Broker will then purchase shares for the remaining amount, after total strike amount and broker fee is covered, and transfer these to your share depository account",
   "exercise.type.sharedepositoryaccount.header": "Share Depository Account",
   "exercise.type.sharedepositoryaccount.description": "In order to transfer your shares to you we need your Share Depository Account account number",
   "exercise.type.sharedepositoryaccount.label": "Share Depository Account Number",
   "exercise.type.sharedepositoryaccount.placeholder": "Share Depository Account",
   "exercise.type.sharedepositoryaccount.checkbox.label": "Share Depository Account is under establishment / not ready",
   "exercise.type.bankaccount.checkbox.label": "I will supply this information later",
   "exercise.type.bankaccount.header": "Bank Account",
   "exercise.type.bankaccount.description": "In order to transfer your funds to you we need your bank account number",
   "exercise.type.bankaccount.label": "Bank Account Number",
   "exercise.type.bankaccount.placeholder": "Bank Account Number",
   "exercise.confirm.exerciseandhold.body": "You have chosen to excercise <strong>{totalQuantity}</strong> {instrumentTerm}. The average strike price is <strong>{averageCost}</strong>. The total strike price/cost of exercising the {instrumentTerm} is <strong>{totalCostOfExercise}</strong>.",
   "exercise.confirm.exerciseandsell.body": "You have chosen to excercise <strong>{totalQuantity}</strong> {instrumentTerm}. The average strike price is <strong>{averageCost}</strong>. The total strike price/cost of exercising the {instrumentTerm} is <strong>{totalCostOfExercise}</strong>. This total cost will be covered by the broker. Net gain, after total strike and broker fee is covered, will be paid as salary by the company.",
   "exercise.confirm.exerciseandsell.body.2": "Note that Estimated gain below is based on last available share price ({sharePrice}). Actual gain will depend on market prices following the exercise window.",
   "exercise.confirm.exerciseandselltocover.body": "You have chosen to excercise <strong>{totalQuantity}</strong> {instrumentTerm}. The average strike price is <strong>{averageCost}</strong>. The total strike price/cost of exercising the {instrumentTerm} is <strong>{totalCostOfExercise}</strong>. This total cost will be covered by the broker. Net gain, after total strike and broker fee is covered, will be paid as salary by the company.",
   "exercise.confirm.exerciseandselltocover.body.2": "Note that Estimated gain below is based on last available share price ({sharePrice}). Actual gain will depend on market prices following the exercise window.",
   "exercise.confirm.table.bankaccount.label": "Bank Account",
   "exercise.confirm.exercise.and.sell.payment.description": "Please transfer the total strike price of {totalPrice} using the payment information below. The full amount must be transferred and registered into the account before {transferDeadline}. If payment is not registered in time, the options will fail to be exercised. The transfer of funds might take several days, we encourage to do this as soon as possible in order for the payment to be registered in time. Note: A confirmation email with the payment information will be sent to you upon confirmation of the order",
   "payment.header": "Payment Information",
   "payment.domestic.account.header": "1. From domestic accounts:",
   "payment.domestic.account.description": "Use bank account number {bankAccountNumber}",
   "payment.domestic.noaccount.description": "Use the bank account number given to you by your employer",
   "payment.foreign.account.header": "2. From foreign accounts:",
   "payment.foreign.noaccount.description": "Use the payment information given to you by your employer",
   "faq.1.header": "Question",
   "faq.1.answer": "Answer... Please transfer the total strike price of {totalPrice} using the payment information below. The full amount must be transferred and registered into the company bank account before {transferDeadline}. If payment is not registered in time, the options will fail to be exercised. The transfer of funds might take several days and we encourage you to do this as soon as possible in order for the payment to be registered on time. A confirmation email with the payment information will be sent to you upon confirmation of the order.",
   "faq.2.header": "Question",
   "faq.2.answer": "Answer... Please transfer the total strike price of {totalPrice} using the payment information below. The full amount must be transferred and registered into the company bank account before {transferDeadline}. If payment is not registered in time, the options will fail to be exercised. The transfer of funds might take several days and we encourage you to do this as soon as possible in order for the payment to be registered on time. A confirmation email with the payment information will be sent to you upon confirmation of the order.",
   "exercise.confirm.header": "Review & Confirm",
   "exercise.confirm.table.header": "Order Summary",
   "exercise.confirm.table.sharedepositoryaccount.label": "Share Depository Account",
   "exercise.confirm.table.note": "Estimated gain is not actual gain",
   "instruments.show.expired": "Show expired",
   "orders.contact.us": "Contact us at {email} if you have any questions or want to cancel your order"
};
