import {Moment} from "moment";

export interface SocSecLine {
    entityName: string,
    internal_employee_id?: string,
    entityId: string,
    programId: string,
    programName: string,
    employeeName: string,
    planName: string,
    subplanName: string,
    grantDate?: Moment,
    vestedDate?: Moment,
    expiryDate?: Moment,
    strike: number,
    quantity: number,
    socSecPercent: number,
    socSecRate: number,
    intrinsicValueLastClosingDate: number,
    earnedRateOB: number,
    intrinsicValueAtEndOfPeriod: number,
    earnedRatePeriod: number,
    earnedRateCB: number,
    costLastClosingDate: number,
    costPerEndOfPeriod: number,
    costOfPeriod: number,
    totalTurnoverRate?: number,
    annualTurnoverRate?: number,
    turnoverEffectOB?: number,
    costOBIncTurnover?: number,
    periodCostIncTurnover?: number,
    turnoverEffectCB?: number,
    costCBIncTurnover?: number,
    mobilityFrom?: Moment,
    mobilityTo?: Moment,
    quantityOB: number,
    quantityCB: number,
}

export interface PrintableSocSecLine {
    entityName: string,
    internal_employee_id?: string,
    employeeName: string,
    planName: string,
    subplanName: string,
    grantDate: string,
    vestedDate: string,
    expiryDate: string,
    strike: string,
    quantity: string,
    socSecRate: string,
    sharePriceOB: string,
    sharePriceCB: string,
    intrinsicValueLastClosingDate: string,
    earnedRateOB: string,
    intrinsicValueAtEndOfPeriod: string,
    earnedRatePeriod: string,
    earnedRateCB: string,
    costLastClosingDate: string,
    costPerEndOfPeriod: string,
    costOfPeriod: string,
    totalTurnoverRate: string,
    annualTurnoverRate: string,
    turnoverEffectOB: string,
    costOBIncTurnover: string,
    periodCostIncTurnover: string,
    turnoverEffectCB: string,
    costCBIncTurnover: string,
    mobilityFrom?: string,
    mobilityTo?: string,
    quantityOB: string,
    quantityCB: string,
}
