export const FETCH_CONTENTS = "FETCH_CONTENTS";
export const FETCH_CONTENTS_FAILED = "FETCH_CONTENTS_FAILED";
export const FETCH_CONTENTS_SUCCEEDED = "FETCH_CONTENTS_SUCCEEDED";

export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const UPDATE_CONTENT_FAILED = "UPDATE_CONTENT_FAILED";
export const UPDATE_CONTENT_SUCCEEDED = "UPDATE_CONTENT_SUCCEEDED";