export const FETCH_DIVIDENDS = "FETCH_DIVIDENDS";
export const FETCH_DIVIDENDS_SUCCEEDED = "FETCH_DIVIDENDS_SUCCEEDED";
export const FETCH_DIVIDENDS_FAILED = "FETCH_DIVIDENDS_FAILED";

export const CREATE_DIVIDEND = "CREATE_DIVIDEND";
export const CREATE_DIVIDEND_SUCCEEDED = "CREATE_DIVIDEND_SUCCEEDED";
export const CREATE_DIVIDEND_FAILED = "CREATE_DIVIDEND_FAILED";
