export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const UPDATE_TRANSACTION_SUCCEEDED = "UPDATE_TRANSACTION_SUCCEEDED";
export const UPDATE_TRANSACTION_FAILED = "UPDATE_TRANSACTION_FAILED";


export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const CREATE_TRANSACTION_SUCCEEDED = "CREATE_TRANSACTION_SUCCEEDED";
export const CREATE_TRANSACTION_FAILED = "CREATE_TRANSACTION_FAILED";